language: python
python: 2.7
sudo: false

install: pip install tox coverage coveralls

script:
  - tox
  # Combine all the coverage reports from the different tox envs:
  - coverage combine
  - coverage report --show-missing

after_success:
  - coveralls

notifications:
    email: false
